# Line trip perturbation scenario

# Simulation parameters
[simulation]
start_time = 0.0
end_time = 20.0
time_step = 0.001
perturb_time = 5.0
save_interval = 0.01

# Component enablement
[enabled_components]
machine = true
avr = true
governor = true

# Perturbation settings
[perturbation]
type = "LINE_TRIP"
line = "1-2"  # Trip line between bus 1 and bus 2